export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const FILTER_MOST_LIKED = "FILTER_MOST_LIKED";
export const FILTER_MOST_COMMENTED = "FILTER_MOST_COMMENTED";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
